FROM node:18-alpine AS build

USER node

RUN mkdir /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node package*.json .

RUN npm install --loglevel=error

COPY --chown=node:node . .

RUN npm run build

EXPOSE 3000

CMD npm run start