version: '3.1'

services:
  api:
    container_name: quem-eu-financio
    restart: always
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      REDIS_HOST: cache
      REDIS_USER: ${REDIS_USER}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    volumes:
      - .:/app
    networks:
      - app-network
    depends_on:
      - cache

  cache:
    image: redis:6.2-alpine
    container_name: cache
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data
    networks:
      - app-network

networks:
  app-network:


volumes:
  cache:
    driver: local
