name: Push-to-EC2

on:
  push:
    branches:
      - feat/configure-github-actions

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the files
      uses: actions/checkout@v2

    - name: Deploy to Server 1
      uses: easingthemes/ssh-deploy@main

      env:
        SSH_PRIVATE_KEY: ${{secrets.EC2_SSH_KEY}}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "./"
        REMOTE_HOST: ${{secrets.HOST_DNS}}
        REMOTE_USER: ${{secrets.USERNAME}}
        TARGET: ${{secrets.TARGET_DIR}}
        EXCLUDE: "**.env"

    - name: Restart the application
      run: docker-compose down
      run: docker-compose up
  